### ISSUE TITLE
When you click "share this view", it should copy the URL to your clipboard instead of opening in a new tab

### ISSUE THREAD

**Issue by rosslh** [rosslh/Mandelbrot.site#20]
The "share this view" element should be made a button instead of a link. When clicked, the URL should be copied and the text of the button should change to "Copied link!" temporarily.

**Comment by shubhankar-shandilya-india** [comment]
Hi @rosslh , I’d like to work on this issue. Could you please assign it to me? Also, just to confirm, when the user clicks on 'Share this view,' it should save the current browser URL to the clipboard, right?

**Comment by rosslh** [comment]
Hey @shubhankar-shandilya-india, that's awesome you're willing to take this on! Thank you. Here's a bit more detail on what you should do.

### How it currently works

- Zoom in or drag the map
- Click the "share this view" link
- A new tab is opened to a mandelbrot.site URL containing some [parameters](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL#parameters). The URL looks something like this:
[`https://mandelbrot.site/?re=-0.69140625&im=-0.14804210296684062&z=4&i=200&e=2&c=turbo&r=false&sharing=true`](https://mandelbrot.site/?re=-0.69140625&im=-0.14804210296684062&z=4&i=200&e=2&c=turbo&r=false&sharing=true)
- If the URL contains a `sharing` parameter, it is removed. Otherwise, all of the parameters are removed.

### How it should work

- Zoom in or drag the map
- Click the "share this view" button (not a link anymore)
- A URL like this is copied to your clipboard:
[`https://mandelbrot.site/?re=-0.69140625&im=-0.14804210296684062&z=4&i=200&e=2&c=turbo&r=false`](https://mandelbrot.site/?re=-0.69140625&im=-0.14804210296684062&z=4&i=200&e=2&c=turbo&r=false)
  - **Note**: we no longer need the `sharing=true` parameter
- The button text changes to `Copied link!`
- 5 seconds later, the button text changes back to `Share this view`

### Where to begin

You'll probably want to take a look at these functions:

- [setConfigFromUrl](https://github.com/rosslh/Mandelbrot.site/blob/master/client/js/main.ts#L338)
  - We no longer need the `sharing` parameter, so remove any references to that. Instead of the current behaviour which is dependant on the `sharing` parameter, running this function should always remove every parameter from the URL.
- [setDomElementValues](https://github.com/rosslh/Mandelbrot.site/blob/master/client/js/MandelbrotMap.ts#L113)
  - Since we no longer have a share link, we don't need to continuously update a link's href whenever the user does something. Instead let's generate the URL when the user clicks the share button.

**Comment by shubhankar-shandilya-india** [comment]
Hi @rosslh, I am facing an error, could you help me set up this project locally?
I have forked the repo, cloned it, went to /client and run npm install, and on npm run start, I am facing this error.
![image](https://github.com/user-attachments/assets/81c5536f-f9ad-49f5-a4aa-c011269a3680)

**Comment by rosslh** [comment]
@shubhankar-shandilya-india You might need to do `npm run build` first. If that doesn't fix it, I'll take a look later.

**Comment by rosslh** [comment]
Resolved in #23, thanks @shubhankar-shandilya-india! 🚀 🥳
